name: Run Robot Framework Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python e instalar dependências
      - name: Install Allure and Robot Framework dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install allure-robotframework

      # 3. Executar testes e gerar relatórios do Allure
      - name: Run Robot Framework tests
        run: |
          mkdir -p reports
          robot --outputdir reports tests/
          allure generate reports --clean -o allure-results

      # 4. Fazer upload dos relatórios como artefatos
      - name: Upload Allure Reports
        uses: actions/upload-artifact@v3
        with:
          name: allure-reports
          path: allure-results

      # 5. (Opcional) Publicar relatório do Allure
      - name: Publish Allure Report
        uses: mikepenz/action-allure-report@v2
        with:
          allure-results: allure-results
